routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('portal', 'PortalController');
Route::resource('portallive', 'PortalLiveController');

app/Portal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Portal extends Model
{
    //
    protected $fillable = [
        'portal_title','portal_detail','portal_date','portal_writer','image_name','image_size','image_type','image_path'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PortalController.php
<?php

namespace App\Http\Controllers;


use Illuminate\Http\Request;
use App\Portal;
use Illuminate\Support\Facades\Storage;

class PortalController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $portal = Portal::all();

        return view('Portal.index', compact('portal'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('portal.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //]
        $request->validate([
            'portal_title'=>'required',
            'portal_detail'=> 'required',
            'portal_date' => 'required',
            'portal_writer' => 'required',
            'file' => 'file|image'

          ]);
          $file = $request->file('file');
          $name = $file->getClientOriginalName();
          $path = $file->store('public/images');

          $portal = new Portal([
            'portal_title' => $request->get('portal_title'),
            'portal_detail'=> $request->get('portal_detail'),
            'portal_date'=> $request->get('portal_date'),
            'portal_writer'=> $request->get('portal_writer'),
            'image_name'=> $name,
            'image_size'=> Storage::size($path),
            'image_type'=> pathinfo($path, PATHINFO_EXTENSION),
            'image_path'=> $path
          ]);
          $portal->save();
          return redirect('/portal')->with('success', 'News has been added');        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $portal = Portal::find($id);

        return view('portal.edit', compact('portal'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $request->validate([
            'portal_title'=>'required',
            'portal_detail'=> 'required',
            'portal_date' => 'required',
            'portal_writer' => 'required',
          ]);
    
          $portal = Portal::find($id);
          $portal->portal_title = $request->get('portal_title');
          $portal->portal_detail = $request->get('portal_detail');
          $portal->portal_date = $request->get('portal_date');
          $portal->portal_writer = $request->get('portal_writer');
          $portal->save();
    
          return redirect('/portal')->with('success', 'News has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $portal = Portal::find($id);
        $portal->delete();
   
        return redirect('/portal')->with('success', 'News has been deleted Successfully');
    }
}

app/Http/Controllers/PortalLiveController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Portal;
use Illuminate\Support\Facades\Storage;

class PortalLiveController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $portal = Portal::orderBy('created_at','desc')->get();
        
        // dd($portal);
        return view('PortalLive.index', compact('portal'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/portal/create.blade.php
@extends('portal.layout')

@section('content')
<style>
.uper {
    margin-top: 40px;
}
</style>
<div class="card uper">
    <div class="card-header">
        Add News
    </div>
    <div class="card-body">
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div><br />
        @endif
        <form method="post" action="{{ route('portal.store') }}" enctype="multipart/form-data">
            <div class="form-group">
                @csrf
                <label for="portal_title">Title:</label>
                <input type="text" class="form-control" name="portal_title" />
            </div>
            <div class="form-group">
                <label for="portal_detail">Content:</label>
                <textarea class="form-control" name="portal_detail" cols="50" rows="10" id="placeOfDeath"></textarea>
            </div>
            <div class="form-group">
                <label for="porta_date">Date:</label>
                <input class="date form-control" type="date" id="datepicker" name="portal_date">
            </div>
            <div class="form-group">
                <label for="quantity">Writer:</label>
                <select class="form-control" id="type" name="portal_writer">
                    <option value="">Select Writer....</option>
                    <option value="Septian Setia Cahya P" >Septian Setia Cahya P</option>
                    <option value="Amanda Putri" >Amanda Putri</option>
                    <option value="Jessica Nolan" >Jessica Nolan</option>
                    <option value="Annisa Safitri" >Annisa Safitri</option>
                    <option value="Wildan Nur Jam" >Wildan Nur Jam</option>
                </select>
            </div>
            <div class="form-group">
                <label for="porta_date">Picture:</label>
                <input class="form-control" type="file" name="file"/>

            </div>
            
            <button type="submit" class="btn btn-primary" style="float:right">Add</button>
        </form>
    </div>
</div>
@endsection

resources/views/portal/edit.blade.php
@extends('portal.layout')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Edit Share
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('portal.update', $portal->id) }}">
        @method('PATCH')
        @csrf

        <div class="form-group">
                @csrf
                <label for="portal_title">Title:</label>
                <input type="text" class="form-control" name="portal_title" value="{{ $portal->portal_title }}" />
            </div>
            <div class="form-group">
                <label for="portal_detail">Content:</label>
                <textarea class="form-control" name="portal_detail" cols="50" rows="10" >{{ $portal->portal_detail }}</textarea>
            </div>
            <div class="form-group">
                <label for="porta_date">Date:</label>
                <input class="date form-control" type="date" id="datepicker" name="portal_date" value="{{ $portal->portal_date }}">
            </div>
            <div class="form-group">
                <label for="quantity">Writer:</label>
                <select class="form-control" id="type" name="portal_writer">
                    <option value="">Select Writer....</option>
                    <option value="Septian Setia Cahya P" {{ $portal->portal_writer == 'Septian Setia Cahya P' ? 'selected' : '' }} >Septian Setia Cahya P</option>
                    <option value="Amanda Putri" {{ $portal->portal_writer == 'Amanda Putri' ? 'selected' : '' }} >Amanda Putri</option>
                    <option value="Jessica Nolan" {{ $portal->portal_writer == 'Jessica Nolan' ? 'selected' : '' }} >Jessica Nolan</option>
                    <option value="Annisa Safitri" {{ $portal->portal_writer == 'Annisa Safitri' ? 'selected' : '' }} >Annisa Safitri</option>
                    <option value="Wildan Nur Jam" {{ $portal->portal_writer == 'Wildan Nur Jam' ? 'selected' : '' }} >Wildan Nur Jam</option>
                </select>
            </div>
            <div class="form-group">
                <label for="porta_date">Picture:</label>
                <img src=" {{ asset('storage/' . $portal->image_path) }}" /> 
                <img src="{{ asset($portal->image_path) }}" alt="" class="card-img-top">
                <input class="form-control" type="file" name="file"/>

            </div>        
        <button type="submit" class="btn btn-primary" style="float:right;">Update</button>
      </form>
  </div>
</div>
@endsection

resources/views/portal/index.blade.php
@extends('portal.layout')

@section('content')
<style>

</style>
<div class="uper">

    @if(session()->get('success'))
    <div class="alert alert-success">
        {{ session()->get('success') }}
    </div><br />
    @endif
    <a href="{{ route('portal.create')}}" class="btn btn-success" style="margin:5px;">Create</a>
    <table class="table ">
        <thead>
            <tr>
                <td>No</td>
                <td>Stock Name</td>
                <td>Stock Price</td>
                <td>Stock Quantity</td>
                <td>Action</td>
            </tr>
        </thead>
        <tbody>
            @foreach($portal as $index => $portaldata)
            
            <?php 
            $dates = explode('-',$portaldata->portal_date);
            $date = $dates[2];
            $month = $dates[1];
            $year = $dates[0];
            $newdate= $date .'-'.$month.'-'.$year;
            ?>
            <tr>
                <td>{{ $index +1 }}</td>
                <td>{{$portaldata->portal_title}}</td>
                <td>{{$newdate}}</td>
                <td>{{$portaldata->portal_writer}}</td>
                <td>
                    <a href="{{ route('portal.edit',$portaldata->id)}}" class="btn btn-primary">Edit</a>
                    <form action="{{ route('portal.destroy', $portaldata->id)}}" method="post" style="display:inline-block !important;">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-danger" type="submit">Delete</button>
                    </form>

                </td>

            </tr>
            @endforeach
        </tbody>
    </table>
    <div>
        @endsection

resources/views/portal/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>ABC News Portal</title>
  <link href="{{ asset('css/app.css') }}" rel="stylesheet" type="text/css" />
</head>
<body>

<div class="jumbotron" style="text-align:center; padding:20px;">
  <h2>News Portal ABC - Admin Page</h2>      
  <p>Your trusted News Portal</p>
</div>
  <div class="container">
    @yield('content')
  </div>
</body>
</html>

resources/views/portallive/index.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>TechNews - HTML and CSS Template</title>

    <!-- favicon -->
    <link href="assets/img/favicon.png" rel=icon>

    <!-- web-fonts -->
    <link href='https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,500' rel='stylesheet' type='text/css'>
    <link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('css/mobile-menu.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('css/offcanvas.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('css/style.css') }}" rel="stylesheet" type="text/css" />
    <!-- Bootstrap -->
    <!-- <link href="assets/css/bootstrap.min.css" rel="stylesheet"> -->

    <!-- font-awesome -->
    <link href="assets/fonts/font-awesome/font-awesome.min.css" rel="stylesheet">
    <!-- Mobile Menu Style -->
    <link href="assets/css/mobile-menu.css" rel="stylesheet">

    <!-- Owl carousel -->
    <link href="assets/css/owl.carousel.css" rel="stylesheet">
    <link href="assets/css/owl.theme.default.min.css" rel="stylesheet">
    <!-- Theme Style -->
    <link href="assets/css/style.css" rel="stylesheet">
</head>

<body id="page-top">
    <div id="main-wrapper">

        <div class="uc-mobile-menu-pusher">
            <div class="content-wrapper">
                <section id="header_section_wrapper" class="header_section_wrapper">
                    <div class="container">
                        <div class="header-section">
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="left_section">
                                        <span class="date">
                                            {{ date('D') }} .
                                        </span>
                                        <!-- Date -->
                                        <span class="time">
                                            {{ date('d-F-Y') }}
                                        </span>
                                        <!-- Time -->
                                        <!-- Top Social Section -->
                                    </div>
                                    <!-- Left Header Section -->
                                </div>
                                <div class="col-md-4">
                                    <div class="logo">
                                        <a href="index.html"><img src="{{ asset('abc.png') }}" style="width:200px;" alt="Tech NewsLogo"></a>
                                    </div>
                                    <!-- Logo Section -->
                                </div>
                                <div class="col-md-4">
                                    <div class="right_section" >
                                        <ul class="nav navbar-nav">
                                            <li><a href="{{ route('portal.index') }}" style="z-index:99;" >Admin Page</a></li>
                                        </ul>
                                        <!-- Language Section -->
                                        <!-- Search Section -->
                                    </div>
                                    <!-- Right Header Section -->
                                </div>
                            </div>
                        </div>
                        <!-- Header Section -->


                        <!-- .navigation-section -->
                    </div>
                    <!-- .container -->
                </section>
                <!-- header_section_wrapper -->

<hr>
                <section id="category_section" class="category_section">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="category_section mobile">
                                    <!----article_title------>
                                    <div class="category_article_wrapper">
                                    @foreach($portal as $index => $portaldata)
                                    <?php 
                                    $dates = explode('-',$portaldata->portal_date);
                                    $date = $dates[2];
                                    $month = $dates[1];
                                    $year = $dates[0];
                                    $newdate= $date .'-'.$month.'-'.$year;
                                    ?>
                                        <div class="row">
                                            <div class="col-md-5">
                                                <div class="top_article_img">
                                                    <a ><img src="{{asset('storage/images/'.$portaldata->image_path)}}"  class="card-img-top">
                                                    </a>
                                                </div>
                                       
                                                <!----top_article_img------>
                                            </div>
                                            <div class="col-md-7">
                                                <div class="category_article_title">
                                                    <h2><a >{{$portaldata->portal_title}}</a></h2>
                                                </div>
                                                <!----category_article_title------>
                                                <div class="category_article_date"><a >{{$newdate}}</a>, by: <a
                                                        >{{$portaldata->portal_writer}}</a></div>
                                                <!----category_article_date------>
                                                <div class="category_article_content">
                                                {{$portaldata->portal_detail}}
                                                </div>
                                                <!----category_article_content------>

                                                <!----media_social------>
                                            </div>
                                        </div>
                                    @endforeach
                                    </div>
                                </div>
                                <!-- Mobile News Section -->



                            </div>
                            <!-- Design News Section -->
                        </div>
                        <!-- Left Section -->


                        <!-- Popular News -->


                        <!-- Most Commented News -->


                        <!--Advertisement-->
                    </div>
                    <!-- Right Section -->

            </div>
            <!-- Row -->

        </div>
        <!-- Container -->

        </section>
        <!-- Category News Section -->



        <section id="footer_section" class="footer_section">

            <div class="footer_bottom_Section">
                <div class="container">
                    <div class="row">
                        <div class="footer">
                            <div class="col-sm-3">
                                <div class="social">
                                    <a class="icons-sm fb-ic"><i class="fa fa-facebook"></i></a>
                                    <!--Twitter-->
                                    <a class="icons-sm tw-ic"><i class="fa fa-twitter"></i></a>
                                    <!--Google +-->
                                    <a class="icons-sm inst-ic"><i class="fa fa-instagram"> </i></a>
                                    <!--Linkedin-->
                                    <a class="icons-sm tmb-ic"><i class="fa fa-tumblr"> </i></a>
                                    <!--Pinterest-->
                                    <a class="icons-sm rss-ic"><i class="fa fa-rss"> </i></a>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <p>&copy; Copyright 2019-ABC NEWS . Design by: <a
                                        href="https://uicookies.com">uiCookies</a>
                                </p>
                            </div>
                            <div class="col-sm-3">
                                <p>Your Trusted News</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <!-- #content-wrapper -->

    </div>
    <!-- .offcanvas-pusher -->

    <a href="#" class="crunchify-top"><i class="fa fa-angle-up" aria-hidden="true"></i></a>

   
</body>

</html>